
[k3s_server]
${K3S_SERVER_INSTANCE_ID} ansible_connection=amazon.aws.aws_ssm ansible_aws_ssm_region=${AWS_REGION} ansible_aws_ssm_bucket_name=${SSM_BUCKET_NAME} ansible_user=ssm-user

[k3s_agent]
${K3S_AGENT_INSTANCE_ID} ansible_connection=amazon.aws.aws_ssm ansible_aws_ssm_region=${AWS_REGION} ansible_aws_ssm_bucket_name=${SSM_BUCKET_NAME} ansible_user=ssm-user

[k3s_cluster:children]
k3s_server
k3s_agent
