---
- name: Create remote Trivy reports directory
  ansible.builtin.file:
    path: /tmp/trivy-reports
    state: directory
    mode: "0755"

- name: Get detailed VulnerabilityReports
  ansible.builtin.command: kubectl get vulnerabilityreports -A -o yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: vulnerability_reports_result
  changed_when: false
  failed_when: false

- name: Save VulnerabilityReports to remote file
  ansible.builtin.copy:
    dest: /tmp/trivy-reports/vulnerabilityreports.yaml
    content: "{{ vulnerability_reports_result.stdout | default('') }}"
    mode: "0644"

- name: Get detailed ConfigAuditReports
  ansible.builtin.command: kubectl get configauditreports -A -o yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: configaudit_reports_result
  changed_when: false
  failed_when: false

- name: Save ConfigAuditReports to remote file
  ansible.builtin.copy:
    dest: /tmp/trivy-reports/configauditreports.yaml
    content: "{{ configaudit_reports_result.stdout | default('') }}"
    mode: "0644"

- name: Get detailed RBAC Assessment Reports
  ansible.builtin.command: kubectl get rbacassessmentreports -A -o yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: rbac_reports_result
  changed_when: false
  failed_when: false


- name: Save RBAC Assessment Reports to remote file
  ansible.builtin.copy:
    dest: /tmp/trivy-reports/rbacreports.yaml
    content: "{{ rbac_reports_result.stdout | default('') }}"
    mode: "0644"

- name: Fetch VulnerabilityReports to runner
  ansible.builtin.fetch:
    src: /tmp/trivy-reports/vulnerabilityreports.yaml
    dest: ../trivy-output/vulnerabilityreports.yaml
    flat: true

- name: Fetch ConfigAuditReports to runner
  ansible.builtin.fetch:
    src: /tmp/trivy-reports/configauditreports.yaml
    dest: ../trivy-output/configauditreports.yaml
    flat: true

- name: Fetch RBAC Reports to runner
  ansible.builtin.fetch:
    src: /tmp/trivy-reports/rbacreports.yaml
    dest: ../trivy-output/rbacreports.yaml
    flat: true