
- name: Prepare K3s nodes
  hosts: k3s_cluster
  become: true
  gather_facts: true

  tasks:
    - name: Run prerequisites
      ansible.builtin.import_role:
        name: k3s
        tasks_from: prerequisites

- name: Install K3s server
  hosts: k3s_server
  become: true
  gather_facts: true

  tasks:
    - name: Install server node
      ansible.builtin.import_role:
        name: k3s
        tasks_from: install_server

- name: Install K3s agent
  hosts: k3s_agent
  become: true
  gather_facts: true

  tasks:
    - name: Install agent node
      ansible.builtin.import_role:
        name: k3s
        tasks_from: install_agent

- name: Validate K3s cluster
  hosts: k3s_server
  become: true
  gather_facts: false

  tasks:
    - name: Validate cluster
      ansible.builtin.import_role:
        name: k3s
        tasks_from: validate
