
- name: Check agent installed
  stat:
    path: /etc/systemd/system/k3s-agent.service
  register: agent

- name: Install agent
  shell: |
    curl -sfL "{{ k3s_install_script_url }}" | sh -s - agent     --server https://{{ k3s_server_private_ip }}:{{ k3s_api_port }}     --token "{{ k3s_token }}"
  when: not agent.stat.exists

- name: Ensure agent started
  systemd:
    name: k3s-agent
    state: started
