---
- name: Check if K3s server binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install K3s server
  ansible.builtin.shell: |
    set -e

    if [ -n "{{ k3s_version }}" ]; then
      export INSTALL_K3S_VERSION="{{ k3s_version }}"
    fi

    curl -sfL "{{ k3s_install_script_url }}" | sh -s - server \
      --token "{{ k3s_token }}" \
      --write-kubeconfig-mode "{{ k3s_write_kubeconfig_mode }}" \
      --tls-san "{{ k3s_tls_san }}" \
      --node-name "{{ inventory_hostname }}" \
      {% if k3s_disable_traefik %} --disable traefik {% endif %} \
      {% if k3s_disable_servicelb %} --disable servicelb {% endif %}
  args:
    executable: /bin/bash
  when: not k3s_binary.stat.exists
  #no_log: true

- name: Ensure K3s server service is enabled and started
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started
    daemon_reload: true

- name: Wait for Kubernetes API on server
  ansible.builtin.command: kubectl get nodes
  register: k3s_api_check
  retries: 18
  delay: 10
  until: k3s_api_check.rc == 0
  changed_when: false