---
- name: Check if K3s agent service exists
  ansible.builtin.stat:
    path: /etc/systemd/system/k3s-agent.service
  register: k3s_agent_service

- name: Wait for K3s server API from agent
  ansible.builtin.wait_for:
    host: "{{ k3s_server_private_ip }}"
    port: "{{ k3s_api_port }}"
    timeout: 180

- name: Install K3s agent
  ansible.builtin.shell: |
    set -e

    if [ -n "{{ k3s_version }}" ]; then
      export INSTALL_K3S_VERSION="{{ k3s_version }}"
    fi

    curl -sfL "{{ k3s_install_script_url }}" | sh -s - agent \
      --server "https://{{ k3s_server_private_ip }}:{{ k3s_api_port }}" \
      --token "{{ k3s_token }}" \
      --node-name "{{ inventory_hostname }}" \
      --node-label "node-role.kubernetes.io/worker=true"
  args:
    executable: /bin/bash
  when: not k3s_agent_service.stat.exists
  #no_log: true

- name: Ensure K3s agent service is enabled and started
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
    daemon_reload: true

- name: Check K3s agent service status
  ansible.builtin.command: systemctl is-active k3s-agent
  register: k3s_agent_status
  changed_when: false
  failed_when: k3s_agent_status.stdout != "active"