
- name: Wait for nodes
  shell: kubectl get nodes --no-headers | wc -l
  register: nodes
  retries: 10
  delay: 10
  until: nodes.stdout|int >= 2

- name: Show nodes
  command: kubectl get nodes
  register: out

- debug:
    var: out.stdout_lines
