---
- name: Wait for two K3s nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    /usr/local/bin/kubectl get nodes --no-headers | wc -l
  register: nodes
  retries: 20
  delay: 15
  until: nodes.stdout | int >= 2
  become: true # Necessário para ler o k3s.yaml
  changed_when: false

- name: Show nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    /usr/local/bin/kubectl get nodes -o wide
  register: out
  become: true
  changed_when: false

- name: Print nodes
  ansible.builtin.debug:
    var: out.stdout_lines
