name: Provision and Install K3s

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

      k3s_version:
        description: "Optional K3s version. Empty = latest stable"
        required: false
        default: ""
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

  ARN_OIDC_TERRAFORM_ROLE: ${{ vars.ARN_OIDC_TERRAFORM_ROLE }}
  ARN_OIDC_ANSIBLE_ROLE: ${{ vars.ARN_OIDC_ANSIBLE_ROLE }}

  TERRAFORM_BUCKET_NAME: ${{ vars.TERRAFORM_BUCKET_NAME }}
  SSM_BUCKET_NAME: ${{ vars.SSM_BUCKET_NAME }}

  ALLOWED_PUBLIC_IP_CIDR: ${{ vars.ALLOWED_PUBLIC_IP_CIDR }}

  K3S_SERVER_INSTANCE_ID: ${{ vars.K3S_SERVER_INSTANCE_ID }}
  K3S_AGENT_INSTANCE_ID: ${{ vars.K3S_AGENT_INSTANCE_ID }}

  K3S_VERSION: ${{ inputs.k3s_version }}

jobs:
  terraform-k3s-security-group:
    name: Terraform K3s Security Group
    runs-on: ubuntu-latest

    outputs:
      k3s_server_public_ip: ${{ steps.tf_outputs.outputs.k3s_server_public_ip }}
      k3s_server_private_ip: ${{ steps.tf_outputs.outputs.k3s_server_private_ip }}
      k3s_agent_private_ip: ${{ steps.tf_outputs.outputs.k3s_agent_private_ip }}
      k3s_security_group_id: ${{ steps.tf_outputs.outputs.k3s_security_group_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ARN_OIDC_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: infra/environments/k3s-lab
        run: |
          terraform init \
            -backend-config="bucket=${TERRAFORM_BUCKET_NAME}" \
            -backend-config="key=k3s-security-group/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        working-directory: infra/environments/k3s-lab
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/environments/k3s-lab
        run: |
          terraform plan \
            -var="aws_region=${AWS_REGION}" \
            -var="k3s_server_instance_id=${K3S_SERVER_INSTANCE_ID}" \
            -var="k3s_agent_instance_id=${K3S_AGENT_INSTANCE_ID}" \
            -var="allowed_public_ip_cidr=${ALLOWED_PUBLIC_IP_CIDR}" \
            -var="arn_oidc_ansible_role=${ARN_OIDC_ANSIBLE_ROLE}" \
            -var="adm_bucket_name=${SSM_BUCKET_NAME}" \
            -out=tfplan

      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        working-directory: infra/environments/k3s-lab
        run: terraform apply -auto-approve tfplan

      - name: Export Terraform outputs
        if: ${{ inputs.action == 'apply' }}
        id: tf_outputs
        working-directory: infra/environments/k3s-lab
        run: |
          echo "k3s_server_public_ip=$(terraform output -raw k3s_server_public_ip)" >> "$GITHUB_OUTPUT"
          echo "k3s_server_private_ip=$(terraform output -raw k3s_server_private_ip)" >> "$GITHUB_OUTPUT"
          echo "k3s_agent_private_ip=$(terraform output -raw k3s_agent_private_ip)" >> "$GITHUB_OUTPUT"
          echo "k3s_security_group_id=$(terraform output -raw k3s_security_group_id)" >> "$GITHUB_OUTPUT"

  install-k3s:
    name: Install K3s with Ansible over SSM
    runs-on: ubuntu-latest
    needs: terraform-k3s-security-group
    #if: ${{ inputs.action == 'apply' }}.  # uncomment
    if: false

    env:
      K3S_SERVER_PUBLIC_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_server_public_ip }}
      K3S_SERVER_PRIVATE_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_server_private_ip }}
      K3S_AGENT_PRIVATE_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_agent_private_ip }}
      K3S_TLS_SAN: ${{ needs.terraform-k3s-security-group.outputs.k3s_server_public_ip }}

      K3S_TOKEN: ${{ secrets.K3S_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for Ansible
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ARN_OIDC_ANSIBLE_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate SSM connectivity (status)
        run: |
          aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=${K3S_SERVER_INSTANCE_ID},${K3S_AGENT_INSTANCE_ID}" \
            --query "InstanceInformationList[*].[InstanceId,PingStatus,PlatformName]" \
            --output table

      - name: Install Ansible dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Install Ansible collections
        working-directory: ansible
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o session-manager-plugin.deb
          sudo dpkg -i session-manager-plugin.deb
          session-manager-plugin --version

      - name: Render Ansible inventory
        working-directory: ansible
        run: |
          envsubst < inventory.ini > inventory.rendered.ini
          mv inventory.rendered.ini inventory.ini

      - name: Show rendered inventory
        working-directory: ansible
        run: cat inventory.ini

      - name: Install K3s
        working-directory: ansible
        run: ansible-playbook playbooks/install-k3s.yml

  trivy-operator:
    name: Install Trivy Operator
    runs-on: ubuntu-latest
    #needs: install-k3s         # uncomment
    needs: terraform-k3s-security-group
    if: ${{ inputs.action == 'apply' }}

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ARN_OIDC_ANSIBLE_ROLE: ${{ vars.ARN_OIDC_ANSIBLE_ROLE }}
      SSM_BUCKET_NAME: ${{ vars.SSM_BUCKET_NAME }}

      K3S_SERVER_INSTANCE_ID: ${{ vars.K3S_SERVER_INSTANCE_ID }}
      K3S_AGENT_INSTANCE_ID: ${{ vars.K3S_AGENT_INSTANCE_ID }}

      K3S_SERVER_PUBLIC_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_server_public_ip }}
      K3S_SERVER_PRIVATE_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_server_private_ip }}
      K3S_AGENT_PRIVATE_IP: ${{ needs.terraform-k3s-security-group.outputs.k3s_agent_private_ip }}

      K3S_TOKEN: ${{ secrets.K3S_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for Ansible
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ARN_OIDC_ANSIBLE_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Ansible dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Install Ansible collections
        working-directory: ansible
        run: ansible-galaxy collection install -r requirements.yml

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o session-manager-plugin.deb
          sudo dpkg -i session-manager-plugin.deb

      - name: Render Ansible inventory
        working-directory: ansible
        run: |
          envsubst < inventory.ini > inventory.rendered.ini
          mv inventory.rendered.ini inventory.ini

      - name: Install Trivy Operator
        working-directory: ansible
        run: ansible-playbook playbooks/install-trivy-operator.yml

      - name: Export Trivy reports
        working-directory: ansible
        run: ansible-playbook playbooks/export-trivy-reports.yml

      - name: Upload Trivy reports to S3
        env:
          ADM_BUCKET_NAME: ${{ vars.ADM_BUCKET_NAME }}
          TRIVY_REPORTS_S3_PREFIX: trivy-reports
        run: |
          set -e

          aws s3 cp trivy-output/vulnerabilityreports.txt \
            "s3://${ADM_BUCKET_NAME}/${TRIVY_REPORTS_S3_PREFIX}/vulnerabilityreports.txt" \
            --content-type text/plain

          aws s3 cp trivy-output/configauditreports.txt \
            "s3://${ADM_BUCKET_NAME}/${TRIVY_REPORTS_S3_PREFIX}/configauditreports.txt" \
            --content-type text/plain

          aws s3 cp trivy-output/rbacreports.txt \
            "s3://${ADM_BUCKET_NAME}/${TRIVY_REPORTS_S3_PREFIX}/rbacreports.txt" \
            --content-type text/plain